echo "Welcome to alexandra.systems"
echo ""
echo "This is basic shell that you can edit, run and build files in running"
echo "on an alpine linux docker container and sent to you live through goTTY"
echo "To view the source code just clone the github repository located at"
echo "github.com/Alexandra-Miller/personal-website"
echo ""
echo "If you not familiar with using linux systems here are some basic commands"
echo "cat [FILE]          - prints FILE contents to output ex. cat contact.txt"
echo "man [COMMAND]       - provides convenient manual regarding [COMMAND]"
echo "cd  [PATH]          - changes working directory to [PATH]"
echo "vi  [FILE]          - opens [FILE] in vi editor. enter :q! to quit"
echo ""
echo "Typing --help after a command will provide more information regarding said"
echo "command and it's use."
